# Generated by Django 5.0.6 on 2026-05-31 06:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Untitled Design', max_length=120)),
                ('canvas', models.JSONField(default=dict)),
                ('preview_images', models.JSONField(blank=True, default=dict)),
                ('print_files', models.JSONField(blank=True, default=dict)),
                ('is_template', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DesignAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('upload', 'Upload'), ('camera', 'Camera'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('saved', 'Saved')], default='upload', max_length=20)),
                ('file', models.FileField(upload_to='design_assets/%Y/%m/')),
                ('url', models.URLField(blank=True)),
                ('mime_type', models.CharField(blank=True, max_length=80)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
